name: flutibre
description: Ebook library management with Calibre database

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  easy_splash_screen:
  sqlite3: ^1.11.2
  file_picker: ^5.0.1
  msix: ^3.13.2
  flutter_form_builder: ^9.0.0
  form_field_validator: ^1.1.0
  io: ^1.0.3
  open_filex: ^4.3.2
  delayed_display: ^2.0.0
  path_provider: ^2.0.13
  flutter_riverpod: ^2.2.0
  permission_handler: ^10.2.0
  pluto_grid: ^7.0.2
  flutter_html: ^3.0.0-beta.1
  image_size_getter: ^2.1.2
  equatable: ^2.0.5
  intl: ^0.18.0
  dropdown_search: ^5.0.6
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/bookshelf-icon.png
    - images/bookshelf-icon2.png
    - images/bookmark-icon.png
    - images/cover.png
    - assets/books/
    - assets/books/Richard Kurjak/ 
    - assets/books/Richard Kurjak/Flutibre user manual (1)/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #- family: Allison
  #fonts:
  #- asset: lib/fonts/Allison-Regular.ttf
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  
  # sign_msix: false, store: true for Windows Store
  # sign_msix: true, store: false for local installer
msix_config:
  display_name: Flutibre
  publisher_display_name: Flutibre
  publisher: CN=32DEFD2D-9D37-49B8-8DD6-DA02364366C0
  sign_msix: true
  identity_name: 8045Flutibre.Flutibre
  msix_version: 1.0.0.0
  logo_path: C:\Users\balza\VSCode\flutibre\images\bookshelf-icon2.png
  capabilities: "internetClient,location,microphone,webcam"
  store: false
  