import 'package:flutibre/models/book.dart';

class DataService {
  List<Book> books = [
    Book(
      id: 1,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/1.jpg',
    ),
    Book(
      id: 2,
      author: 'Kiss Jenő',
      title: 'tesztelő',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/2.jpg',
    ),
    Book(
      id: 3,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/3.jpg',
    ),
    Book(
      id: 4,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/4.jpg',
    ),
    Book(
      id: 5,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/5.jpg',
    ),
    Book(
      id: 6,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/6.jpg',
    ),
    Book(
      id: 7,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/7.jpg',
    ),
    Book(
      id: 8,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/8.jpg',
    ),
    Book(
      id: 9,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/9.jpg',
    ),
    Book(
      id: 10,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/10.jpg',
    ),
    Book(
      id: 11,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/11.jpg',
    ),
    Book(
      id: 12,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/12.jpg',
    ),
    Book(
      id: 13,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/13.jpg',
    ),
    Book(
      id: 14,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/14.jpg',
    ),
    Book(
      id: 15,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/15.jpg',
    ),
    Book(
      id: 16,
      author: 'Kurják Richárd',
      title: 'programozó',
      series: 'Idő kerek',
      language: 'magyar',
      publisher: 'Marvel',
      path: 'images/16.jpg',
    ),
  ];

  List<Book> getListBooks() {
    return books;
  }
}
